name: Build wheels

on:
    workflow_dispatch:
        inputs:
            gdal_version:
                description: 'GDAL version to build'
                required: true
                default: '3.9.2'

env:
    GDAL_VERSION: ${{ github.event.inputs.gdal_version }}

jobs:
    build:
        runs-on: ${{ matrix.os }}
        defaults:
          run:
            shell: bash -el {0}
        strategy:
            matrix:
                os: [
                    macos-13, # macOS Ventura (13) - Intel
                    macos-14, # macOS Sonoma (14) - Apple Silicon
                    ubuntu-24.04,
                    windows-2022,
                ]
            fail-fast: false
        steps:
            - uses: actions/checkout@v4
            - uses: conda-incubator/setup-miniconda@v3
              with:
                auto-update-conda: true
            - name: Install GDAL
              id: install-gdal
              run: |
                conda install -c conda-forge libgdal=$GDAL_VERSION
                echo "GDAL_BIN=$CONDA_PREFIX/bin" >> $GITHUB_OUTPUT
            - name: Download/unpack GDAL Python source distribution
              run: |
                curl -L -o gdal.tar.gz https://pypi.io/packages/source/g/gdal/gdal-$GDAL_VERSION.tar.gz
                tar -xzf gdal.tar.gz
            - name: Build wheels
              uses: pypa/cibuildwheel@v2.22
              env:
                CIBW_ENVIRONMENT: PATH=${{ steps.install-gdal.outputs.GDAL_BIN }}:$PATH
              with:
                package-dir: gdal-$GDAL_VERSION
            - uses: actions/upload-artifact@v4
              with:
                name: wheels-${{ matrix.os }}-${{ strategy.job-index }}
                path: ./wheelhouse/*.whl